version: "3"

services:
  app:
    build: .
    restart: always
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s ./.docker/entrypoint-dev.sh
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - mysql
  mysql:
    build: .docker/mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker/dbdata:/var/lib/mysql
